# -*- coding: utf-8 -*-
"""Bab 10 - Pebryan.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1na82BKPhyOIs28Tmz8UXysHHQId4cqI3

### QueueLinkedList
"""

# Membuat class Node
# Node digunakan untuk menyimpan data dan alamat node berikutnya
class Node:

    # Constructor Node
    def __init__(self, value=None):

        # Menyimpan nilai/data node
        self.value = value

        # Pointer ke node berikutnya
        self.next = None

    # Mengubah object menjadi string
    def __str__(self):
        return str(self.value)


# Membuat class LinkedList
class LinkedList:

    # Constructor LinkedList
    def __init__(self):

        # Node pertama
        self.head = None

        # Node terakhir
        self.tail = None


# Membuat class Queue menggunakan LinkedList
class Queue:

    # Constructor Queue
    def __init__(self):

        # Membuat object LinkedList
        self.linkedList = LinkedList()

    # Menampilkan isi queue
    def __str__(self):

        # Mengubah setiap node menjadi string
        values = [str(x) for x in self.linkedList]

        return ' '.join(values)

    # Menambahkan data ke belakang queue
    def enqueue(self, value):

        # Membuat node baru
        newNode = Node(value)

        # Jika queue kosong
        if self.linkedList.head == None:
            self.linkedList.head = newNode
            self.linkedList.tail = newNode

        # Jika queue sudah berisi data
        else:
            self.linkedList.tail.next = newNode
            self.linkedList.tail = newNode

    # Mengecek apakah queue kosong
    def isEmpty(self):

        if self.linkedList.head == None:
            return True

        else:
            return False

    # Menghapus data paling depan queue (FIFO)
    def dequeue(self):

        # Jika queue kosong
        if self.isEmpty():
            return "There is not any node in the Queue"

        else:
            # Menyimpan node pertama
            tempNode = self.linkedList.head

            # Jika hanya ada satu node
            if self.linkedList.head == self.linkedList.tail:
                self.linkedList.head = None
                self.linkedList.tail = None

            # Jika ada lebih dari satu node
            else:
                self.linkedList.head = self.linkedList.head.next

            # Mengembalikan node yang dihapus
            return tempNode

    # Melihat data paling depan tanpa menghapus
    def peek(self):

        # Jika queue kosong
        if self.isEmpty():
            return "There is not any node in the Queue"

        else:
            return self.linkedList.head

    # Menghapus seluruh isi queue
    def delete(self):

        self.linkedList.head = None
        self.linkedList.tail = None

# Contoh penggunaan Queue

# custQueue = Queue()

# Menambahkan data ke queue
# custQueue.enqueue(1)
# custQueue.enqueue(2)
# custQueue.enqueue(3)

# Menampilkan isi queue
# print(custQueue)

# Melihat data paling depan
# print(custQueue.peek())

# Queue tetap sama karena peek tidak menghapus data
# print(custQueue)

"""### AVL"""

# Mengimpor Queue berbasis Linked List
import QueueLinkedList as queue


# Membuat class AVLNode
# AVL Tree adalah Binary Search Tree yang selalu seimbang
class AVLNode:

    # Constructor
    def __init__(self, data):

        # Menyimpan data node
        self.data = data

        # Anak kiri
        self.leftChild = None

        # Anak kanan
        self.rightChild = None

        # Tinggi node
        self.height = 1


# Traversal Preorder
# Root -> Left -> Right
def preOrderTraversal(rootNode):

    if not rootNode:
        return

    print(rootNode.data)

    preOrderTraversal(rootNode.leftChild)
    preOrderTraversal(rootNode.rightChild)


# Traversal Inorder
# Left -> Root -> Right
def inOrderTraversal(rootNode):

    if not rootNode:
        return

    inOrderTraversal(rootNode.leftChild)

    print(rootNode.data)

    inOrderTraversal(rootNode.rightChild)


# Traversal Postorder
# Left -> Right -> Root
def postOrderTraversal(rootNode):

    if not rootNode:
        return

    postOrderTraversal(rootNode.leftChild)
    postOrderTraversal(rootNode.rightChild)

    print(rootNode.data)


# Traversal Level Order (BFS)
def levelOrderTraversal(rootNode):

    if not rootNode:
        return

    else:
        customQueue = queue.Queue()
        customQueue.enqueue(rootNode)

        while not(customQueue.isEmpty()):

            root = customQueue.dequeue()

            print(root.value.data)

            if root.value.leftChild is not None:
                customQueue.enqueue(root.value.leftChild)

            if root.value.rightChild is not None:
                customQueue.enqueue(root.value.rightChild)


# Mencari node pada AVL Tree
def searchNode(rootNode, nodeValue):

    if rootNode.data == nodeValue:
        print("The value is found")

    elif nodeValue < rootNode.data:

        if rootNode.leftChild.data == nodeValue:
            print("The value is found")

        else:
            searchNode(rootNode.leftChild, nodeValue)

    else:

        if rootNode.rightChild.data == nodeValue:
            print("The value is found")

        else:
            searchNode(rootNode.rightChild, nodeValue)


# Mengambil tinggi node
def getHeight(rootNode):

    if not rootNode:
        return 0

    return rootNode.height


# Rotasi kanan (Right Rotation)
def rightRotate(disbalanceNode):

    # Node baru menjadi root
    newRoot = disbalanceNode.leftChild

    # Mengatur hubungan node
    disbalanceNode.leftChild = disbalanceNode.leftChild.rightChild
    newRoot.rightChild = disbalanceNode

    # Update tinggi node
    disbalanceNode.height = (
        1 + max(
            getHeight(disbalanceNode.leftChild),
            getHeight(disbalanceNode.rightChild)
        )
    )

    newRoot.height = (
        1 + max(
            getHeight(newRoot.leftChild),
            getHeight(newRoot.rightChild)
        )
    )

    return newRoot


# Rotasi kiri (Left Rotation)
def leftRotate(disbalanceNode):

    # Node baru menjadi root
    newRoot = disbalanceNode.rightChild

    # Mengatur hubungan node
    disbalanceNode.rightChild = disbalanceNode.rightChild.leftChild
    newRoot.leftChild = disbalanceNode

    # Update tinggi node
    disbalanceNode.height = (
        1 + max(
            getHeight(disbalanceNode.leftChild),
            getHeight(disbalanceNode.rightChild)
        )
    )

    newRoot.height = (
        1 + max(
            getHeight(newRoot.leftChild),
            getHeight(newRoot.rightChild)
        )
    )

    return newRoot


# Menghitung Balance Factor
def getBalance(rootNode):

    if not rootNode:
        return 0

    return (
        getHeight(rootNode.leftChild)
        - getHeight(rootNode.rightChild)
    )


# Menambahkan node ke AVL Tree
def insertNode(rootNode, nodeValue):

    # Membuat node baru jika root kosong
    if not rootNode:
        return AVLNode(nodeValue)

    elif nodeValue < rootNode.data:
        rootNode.leftChild = insertNode(
            rootNode.leftChild,
            nodeValue
        )

    else:
        rootNode.rightChild = insertNode(
            rootNode.rightChild,
            nodeValue
        )

    # Update tinggi node
    rootNode.height = (
        1 + max(
            getHeight(rootNode.leftChild),
            getHeight(rootNode.rightChild)
        )
    )

    # Hitung balance factor
    balance = getBalance(rootNode)

    # Left Left Case
    if balance > 1 and nodeValue < rootNode.leftChild.data:
        return rightRotate(rootNode)

    # Left Right Case
    if balance > 1 and nodeValue > rootNode.leftChild.data:
        rootNode.leftChild = leftRotate(rootNode.leftChild)
        return rightRotate(rootNode)

    # Right Right Case
    if balance < -1 and nodeValue > rootNode.rightChild.data:
        return leftRotate(rootNode)

    # Right Left Case
    if balance < -1 and nodeValue < rootNode.rightChild.data:
        rootNode.rightChild = rightRotate(rootNode.rightChild)
        return leftRotate(rootNode)

    return rootNode


# Mengambil node dengan nilai terkecil
def getMinValueNode(rootNode):

    if rootNode is None or rootNode.leftChild is None:
        return rootNode

    return getMinValueNode(rootNode.leftChild)


# Menghapus node dari AVL Tree
def deleteNode(rootNode, nodeValue):

    if not rootNode:
        return rootNode

    elif nodeValue < rootNode.data:
        rootNode.leftChild = deleteNode(
            rootNode.leftChild,
            nodeValue
        )

    elif nodeValue > rootNode.data:
        rootNode.rightChild = deleteNode(
            rootNode.rightChild,
            nodeValue
        )

    else:

        # Tidak memiliki child kiri
        if rootNode.leftChild is None:
            temp = rootNode.rightChild
            rootNode = None
            return temp

        # Tidak memiliki child kanan
        elif rootNode.rightChild is None:
            temp = rootNode.leftChild
            rootNode = None
            return temp

        # Memiliki dua child
        temp = getMinValueNode(rootNode.rightChild)

        rootNode.data = temp.data

        rootNode.rightChild = deleteNode(
            rootNode.rightChild,
            temp.data
        )

    # Hitung balance factor
    balance = getBalance(rootNode)

    # Left Left Case
    if balance > 1 and getBalance(rootNode.leftChild) >= 0:
        return rightRotate(rootNode)

    # Right Right Case
    if balance < -1 and getBalance(rootNode.rightChild) <= 0:
        return leftRotate(rootNode)

    # Left Right Case
    if balance > 1 and getBalance(rootNode.leftChild) < 0:
        rootNode.leftChild = leftRotate(rootNode.leftChild)
        return rightRotate(rootNode)

    # Right Left Case
    if balance < -1 and getBalance(rootNode.rightChild) > 0:
        rootNode.rightChild = rightRotate(rootNode.rightChild)
        return leftRotate(rootNode)

    return rootNode


# Menghapus seluruh AVL Tree
def deleteAVL(rootNode):

    rootNode.data = None
    rootNode.leftChild = None
    rootNode.rightChild = None

    return "The AVL has been successfully deleted"



# Membuat AVL Tree
newAVL = AVLNode(5)

# Menambahkan node
newAVL = insertNode(newAVL, 10)
newAVL = insertNode(newAVL, 15)
newAVL = insertNode(newAVL, 20)

# Menghapus seluruh AVL Tree
deleteAVL(newAVL)

# Menampilkan AVL Tree dengan Level Order Traversal
levelOrderTraversal(newAVL)

"""### Trie"""

# Membuat class TrieNode
# Setiap node menyimpan karakter dan child-node
class TrieNode:

    # Constructor
    def __init__(self):

        # Menyimpan child dalam bentuk dictionary
        self.children = {}

        # Menandakan akhir sebuah kata
        self.endOfString = False


# Membuat class Trie
class Trie:

    # Constructor
    def __init__(self):

        # Membuat root node
        self.root = TrieNode()

    # Menambahkan kata ke Trie
    def insertString(self, word):

        # Mulai dari root
        current = self.root

        # Menelusuri setiap karakter
        for i in word:

            ch = i

            # Mencari karakter dalam children
            node = current.children.get(ch)

            # Jika karakter belum ada
            if node == None:

                # Membuat node baru
                node = TrieNode()

                # Menambahkan ke dictionary children
                current.children.update({ch: node})

            # Pindah ke node berikutnya
            current = node

        # Menandai akhir kata
        current.endOfString = True

        print("Successfully inserted")

    # Mencari kata dalam Trie
    def searchString(self, word):

        # Mulai dari root
        currentNode = self.root

        # Menelusuri setiap karakter
        for i in word:

            node = currentNode.children.get(i)

            # Jika karakter tidak ditemukan
            if node == None:
                return False

            currentNode = node

        # Jika benar-benar akhir kata
        if currentNode.endOfString == True:
            return True

        else:
            return False


# Menghapus kata dari Trie
def deleteString(root, word, index):

    # Mengambil karakter saat ini
    ch = word[index]

    # Mengambil node karakter
    currentNode = root.children.get(ch)

    canThisNodeBeDeleted = False

    # Jika node memiliki lebih dari satu child
    if len(currentNode.children) > 1:

        deleteString(currentNode, word, index + 1)

        return False

    # Jika berada di karakter terakhir
    if index == len(word) - 1:

        # Jika masih memiliki child
        if len(currentNode.children) >= 1:

            # Hanya hilangkan penanda akhir kata
            currentNode.endOfString = False

            return False

        else:
            # Hapus node dari parent
            root.children.pop(ch)

            return True

    # Jika node juga merupakan akhir kata lain
    if currentNode.endOfString == True:

        deleteString(currentNode, word, index + 1)

        return False

    # Rekursif ke karakter berikutnya
    canThisNodeBeDeleted = deleteString(
        currentNode,
        word,
        index + 1
    )

    # Jika child bisa dihapus
    if canThisNodeBeDeleted == True:

        root.children.pop(ch)

        return True

    else:
        return False



# Membuat object Trie
newTrie = Trie()

# Menambahkan kata "App"
newTrie.insertString("App")

# Menambahkan kata "Appl"
newTrie.insertString("Appl")

# Menghapus kata "App"
deleteString(newTrie.root, "App", 0)

# Mengecek apakah "App" masih ada
print(newTrie.searchString("App"))

"""### BinaryHeap"""

# Membuat class Heap
# Heap disimpan menggunakan array (list)
class Heap:

    # Constructor
    def __init__(self, size):

        # Membuat list dengan index dimulai dari 1
        self.customList = (size + 1) * [None]

        # Jumlah node yang digunakan
        self.heapSize = 0

        # Kapasitas maksimum heap
        self.maxSize = size + 1


# Menampilkan nilai root heap
def peekofHeap(rootNode):

    if not rootNode:
        return

    else:
        return rootNode.customList[1]


# Mengembalikan jumlah node dalam heap
def sizeofHeap(rootNode):

    if not rootNode:
        return

    else:
        return rootNode.heapSize


# Traversal Level Order
def levelOrderTraversal(rootNode):

    if not rootNode:
        return

    else:
        for i in range(1, rootNode.heapSize + 1):
            print(rootNode.customList[i])


# Heapify saat insert
def heapifyTreeInsert(rootNode, index, heapType):

    # Menghitung parent node
    parentIndex = int(index / 2)

    # Jika sudah sampai root
    if index <= 1:
        return

    # Untuk Min Heap
    if heapType == "Min":

        if rootNode.customList[index] < rootNode.customList[parentIndex]:

            temp = rootNode.customList[index]
            rootNode.customList[index] = rootNode.customList[parentIndex]
            rootNode.customList[parentIndex] = temp

        heapifyTreeInsert(rootNode, parentIndex, heapType)

    # Untuk Max Heap
    elif heapType == "Max":

        if rootNode.customList[index] > rootNode.customList[parentIndex]:

            temp = rootNode.customList[index]
            rootNode.customList[index] = rootNode.customList[parentIndex]
            rootNode.customList[parentIndex] = temp

        heapifyTreeInsert(rootNode, parentIndex, heapType)


# Menambahkan node ke heap
def inserNode(rootNode, nodeValue, heapType):

    # Mengecek apakah heap penuh
    if rootNode.heapSize + 1 == rootNode.maxSize:
        return "The Binary Heap is Full"

    # Menambahkan node di akhir heap
    rootNode.customList[rootNode.heapSize + 1] = nodeValue

    rootNode.heapSize += 1

    # Menyeimbangkan heap
    heapifyTreeInsert(
        rootNode,
        rootNode.heapSize,
        heapType
    )

    return "The value has been successfully inserted"


# Heapify saat extract/delete root
def heapifyTreeExtract(rootNode, index, heapType):

    leftIndex = index * 2
    rightIndex = index * 2 + 1

    swapChild = 0

    # Tidak memiliki child
    if rootNode.heapSize < leftIndex:
        return

    # Hanya memiliki child kiri
    elif rootNode.heapSize == leftIndex:

        if heapType == "Min":

            if rootNode.customList[index] > rootNode.customList[leftIndex]:

                temp = rootNode.customList[index]
                rootNode.customList[index] = rootNode.customList[leftIndex]
                rootNode.customList[leftIndex] = temp

            return

        else:

            if rootNode.customList[index] < rootNode.customList[leftIndex]:

                temp = rootNode.customList[index]
                rootNode.customList[index] = rootNode.customList[leftIndex]
                rootNode.customList[leftIndex] = temp

            return

    else:

        # Min Heap
        if heapType == "Min":

            if rootNode.customList[leftIndex] < rootNode.customList[rightIndex]:
                swapChild = leftIndex
            else:
                swapChild = rightIndex

            if rootNode.customList[index] > rootNode.customList[swapChild]:

                temp = rootNode.customList[index]
                rootNode.customList[index] = rootNode.customList[swapChild]
                rootNode.customList[swapChild] = temp

        # Max Heap
        else:

            if rootNode.customList[leftIndex] > rootNode.customList[rightIndex]:
                swapChild = leftIndex
            else:
                swapChild = rightIndex

            if rootNode.customList[index] < rootNode.customList[swapChild]:

                temp = rootNode.customList[index]
                rootNode.customList[index] = rootNode.customList[swapChild]
                rootNode.customList[swapChild] = temp

    # Rekursif sampai heap kembali valid
    heapifyTreeExtract(rootNode, swapChild, heapType)


# Mengambil dan menghapus root heap
def extractNode(rootNode, heapType):

    if rootNode.heapSize == 0:
        return

    else:
        # Menyimpan root
        extractedNode = rootNode.customList[1]

        # Memindahkan node terakhir ke root
        rootNode.customList[1] = rootNode.customList[rootNode.heapSize]

        # Menghapus node terakhir
        rootNode.customList[rootNode.heapSize] = None

        rootNode.heapSize -= 1

        # Menyeimbangkan heap kembali
        heapifyTreeExtract(rootNode, 1, heapType)

        return extractedNode


# Menghapus seluruh Binary Heap
def deleteEntireBP(rootNode):

    rootNode.customList = None



# Membuat Heap dengan kapasitas 5
newHeap = Heap(5)

# Menambahkan data ke Max Heap
inserNode(newHeap, 4, "Max")
inserNode(newHeap, 5, "Max")
inserNode(newHeap, 2, "Max")
inserNode(newHeap, 1, "Max")

# Menghapus seluruh heap
deleteEntireBP(newHeap)

# Menampilkan heap
levelOrderTraversal(newHeap)